version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes: 
      - ./mongodb:/data/db
      
  express-service:
    image: rb/coronahelper
    build: .
    environment:
      ENV: PROD
      MONGO_URI_PROD: mongodb://mongo:27017/coronahelper?authSource=admin
      PORT: 8888
      USER: admin
      PASS: password
    
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    restart: always


  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_AUTH_DATABASE: coronahelper